"""NexusMD — Ligand File Parser Service

Parses SDF and MOL2 files into a list of dicts suitable for docking.
Each dict has the shape: {"name": str, "smiles": str, "mol_block": str}

RDKit is used for structure parsing and SMILES generation.
If RDKit is unavailable the functions raise ImportError early so the
caller can return a meaningful HTTP 500 rather than a cryptic crash.
"""

import logging
import re
from pathlib import Path
from typing import List

logger = logging.getLogger("nexusmd.ligand_parser")


# ── SMILES generation ──────────────────────────────────────────

def mol_to_smiles(mol_block: str) -> str:
    """Convert a MOL/SDF mol-block string to a canonical SMILES string.

    Tries multiple strategies:
    1. Parse with sanitization (strict, for clean structures)
    2. Parse without sanitization (lenient, for problematic structures)
    3. Extract SMILES from SDF data fields if present

    Returns an empty string if all strategies fail.
    """
    try:
        from rdkit import Chem  # type: ignore

        # Strategy 1: Parse with sanitization (strict)
        mol = Chem.MolFromMolBlock(mol_block, sanitize=True, removeHs=True)
        if mol is not None:
            smi = Chem.MolToSmiles(mol, canonical=True)
            if smi:
                return smi

        # Strategy 2: Parse without sanitization (lenient)
        mol = Chem.MolFromMolBlock(mol_block, sanitize=False, removeHs=False)
        if mol is not None:
            try:
                Chem.SanitizeMol(mol)
            except Exception:
                pass  # Sanitization failed, but we have a mol object

            try:
                mol = Chem.RemoveHs(mol)
            except Exception:
                pass  # RemoveHs failed, continue with hydrogens present

            smi = Chem.MolToSmiles(mol, canonical=True)
            if smi:
                return smi

        # Strategy 3: Look for SMILES in SDF data fields
        smi_from_field = _extract_smiles_from_sdf(mol_block)
        if smi_from_field:
            return smi_from_field

        logger.warning("mol_to_smiles: Could not generate SMILES from mol-block")
        return ""
    except Exception as exc:
        logger.debug(f"mol_to_smiles failed: {exc}")
        return ""


def _extract_smiles_from_sdf(mol_block: str) -> str:
    """Try to extract SMILES from SDF data fields (> <SMILES>, etc.)."""
    for field_name in ["SMILES", "SMILES_CANONICAL", "CANONICAL_SMILES", "smi"]:
        pattern = rf">\s*<{field_name}>\s*\n([^\n]+)"
        match = re.search(pattern, mol_block, re.IGNORECASE)
        if match:
            candidate = match.group(1).strip()
            if candidate:
                logger.debug(f"Extracted SMILES from <{field_name}>: {candidate}")
                return candidate

    return ""


def _mol2_block_to_smiles(mol2_block: str) -> str:
    """Convert a MOL2 block string to a canonical SMILES string.

    Tries multiple strategies similar to mol_to_smiles().
    """
    try:
        from rdkit import Chem  # type: ignore

        # Strategy 1: Parse with sanitization (strict)
        mol = Chem.MolFromMol2Block(mol2_block, sanitize=True, removeHs=True)
        if mol is not None:
            smi = Chem.MolToSmiles(mol, canonical=True)
            if smi:
                return smi

        # Strategy 2: Parse without sanitization (lenient)
        mol = Chem.MolFromMol2Block(mol2_block, sanitize=False, removeHs=False)
        if mol is not None:
            try:
                Chem.SanitizeMol(mol)
            except Exception:
                pass

            try:
                mol = Chem.RemoveHs(mol)
            except Exception:
                pass  # RemoveHs failed, continue with hydrogens present

            smi = Chem.MolToSmiles(mol, canonical=True)
            if smi:
                return smi

        logger.warning("_mol2_block_to_smiles: Could not generate SMILES from mol2-block")
        return ""
    except Exception as exc:
        logger.debug(f"_mol2_block_to_smiles failed: {exc}")
        return ""


# ── SDF parser ─────────────────────────────────────────────────

def parse_sdf_file(file_path: Path) -> List[dict]:
    """Parse an SDF file and return a list of molecule dicts.

    Each dict contains:
        name      – molecule name (from title line or <NAME> property)
        smiles    – canonical SMILES generated by RDKit (empty on failure)
        mol_block – raw MOL block text (without the $$$$ terminator)

    Raises:
        ValueError  – file is empty or contains no parseable molecules
        FileNotFoundError – file does not exist
    """
    file_path = Path(file_path)
    if not file_path.exists():
        raise FileNotFoundError(f"SDF file not found: {file_path}")

    raw = file_path.read_text(encoding="utf-8", errors="replace").strip()
    if not raw:
        raise ValueError("SDF file is empty")

    # Split on the $$$$ record separator; each chunk is one molecule block
    records = re.split(r"\$\$\$\$", raw)
    # The last element after the final $$$$ is typically empty
    records = [r.strip() for r in records if r.strip()]

    if not records:
        raise ValueError("No molecules found in SDF file")

    molecules: List[dict] = []
    failed_count = 0
    for idx, mol_block in enumerate(records):
        name = _extract_sdf_name(mol_block, idx)
        smiles = mol_to_smiles(mol_block)

        if not smiles:
            failed_count += 1
            logger.warning(f"SDF record {idx} ({name!r}): Could not generate SMILES")

        molecules.append({
            "name": name,
            "smiles": smiles,
            "mol_block": mol_block,
        })
        logger.debug(f"SDF record {idx}: name={name!r} smiles={smiles!r}")

    if not molecules:
        raise ValueError("No molecules could be parsed from SDF file")

    if failed_count > 0:
        logger.warning(
            f"Failed to generate SMILES for {failed_count}/{len(molecules)} molecules"
        )

    logger.info(f"Parsed {len(molecules)} molecule(s) from {file_path.name}")
    return molecules


def _extract_sdf_name(mol_block: str, fallback_index: int) -> str:
    """Extract the molecule name from an SDF mol-block.

    Priority:
    1. The ``> <NAME>`` (or ``> <MOLNAME>``) data field
    2. The first line of the mol-block (the title line in V2000/V3000 format)
    3. A generated name ``Ligand-{n}``
    """
    # 1. Look for a named data field: > <NAME> or > <MOLNAME> etc.
    name_field = re.search(
        r">\s*<(?:NAME|MOLNAME|Molecule Name|mol_name)>\s*\n([^\n]+)",
        mol_block,
        re.IGNORECASE,
    )
    if name_field:
        candidate = name_field.group(1).strip()
        if candidate:
            return candidate

    # 2. Title line (first non-empty line of the mol-block)
    for line in mol_block.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped

    # 3. Fallback
    return f"Ligand-{fallback_index + 1}"


# ── MOL2 parser ────────────────────────────────────────────────

def parse_mol2_file(file_path: Path) -> List[dict]:
    """Parse a MOL2 file and return a list of molecule dicts.

    MOL2 files can technically contain multiple molecules separated by
    ``@<TRIPOS>MOLECULE`` sections.  Each molecule is returned as a dict
    with the same shape as :func:`parse_sdf_file`.

    Raises:
        ValueError  – file is empty or contains no parseable molecules
        FileNotFoundError – file does not exist
    """
    file_path = Path(file_path)
    if not file_path.exists():
        raise FileNotFoundError(f"MOL2 file not found: {file_path}")

    raw = file_path.read_text(encoding="utf-8", errors="replace").strip()
    if not raw:
        raise ValueError("MOL2 file is empty")

    # Split into per-molecule blocks on the @<TRIPOS>MOLECULE marker
    # Keep the marker as part of each block so RDKit can parse it
    blocks = re.split(r"(?=@<TRIPOS>MOLECULE)", raw, flags=re.IGNORECASE)
    blocks = [b.strip() for b in blocks if b.strip()]

    if not blocks:
        raise ValueError("No molecules found in MOL2 file")

    molecules: List[dict] = []
    for idx, block in enumerate(blocks):
        name = _extract_mol2_name(block, idx)
        smiles = _mol2_block_to_smiles(block)
        molecules.append({
            "name": name,
            "smiles": smiles,
            "mol_block": block,
        })
        logger.debug(f"MOL2 record {idx}: name={name!r} smiles={smiles!r}")

    if not molecules:
        raise ValueError("No molecules could be parsed from MOL2 file")

    logger.info(f"Parsed {len(molecules)} molecule(s) from {file_path.name}")
    return molecules


def _extract_mol2_name(mol2_block: str, fallback_index: int) -> str:
    """Extract the molecule name from a MOL2 block.

    The name is on the line immediately following ``@<TRIPOS>MOLECULE``.
    """
    lines = mol2_block.splitlines()
    for i, line in enumerate(lines):
        if line.strip().upper() == "@<TRIPOS>MOLECULE":
            # The very next non-empty line is the molecule name
            for j in range(i + 1, len(lines)):
                candidate = lines[j].strip()
                if candidate:
                    return candidate
            break

    return f"Ligand-{fallback_index + 1}"
